### ISSUE TITLE
File name for Lorenz96

### ISSUE THREAD

**Issue by ablancha** [arbabiha/StochasticModelingwData#1]
Hi Hassan,

I believe that in `Lorenz96.py`, Line 179 should read

```python
data2=sio.loadmat('./results/LorenzModel_r3_t1000_ns1')
```

instead of

```python
data2=sio.loadmat('./results/LorenzModel_r3_t1000_ns1.mat')
```

In the current version `scipy.io` throws an error because it's looking for a `.mat` file.

Best,
Antoine

**Comment by arbabiha** [comment]
Fixed it, thanks for raising the issue!
